nfs-common:
# NOTE(mnaser): Some of these packages might not be needed
#               so we should clean them up later.
dhcp-client:
  when: DISTRO_NAME == 'rocky'
logrotate:
  when: DISTRO_NAME == 'rocky'
nftables:
  when: DISTRO_NAME == 'rocky'
qemu-guest-agent:
  when: DISTRO_NAME == 'rocky'
rsyslog:
  when: DISTRO_NAME == 'rocky'
selinux-policy-targeted:
  when: DISTRO_NAME == 'rocky'
