name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/kubernetes.sh
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/capo-image-elements
          commit-message: "chore(deps): update kubernetes"
          signoff: true
          title: "chore(deps): update kubernetes"
          body: |
            ## Automated Kubernetes Version Update
            This PR updates the Kubernetes versions in the CI workflow to the latest maintained versions.
            Source: https://endoflife.date/kubernetes
          delete-branch: true
          branch: bump/kubernetes

