name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cni-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/cni-plugins.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/capo-image-elements
          commit-message: "chore(deps): update cni-plugins"
          signoff: true
          branch: bump/cni-plugins
          delete-branch: true
          title: "chore(deps): update cni-plugins"
          body: |
            ## Automated `cni-plugins` update

            This PR updates the `cni-plugins` binaries to the latest versions.

  containerd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/containerd.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/capo-image-elements
          commit-message: "chore(deps): update containerd"
          signoff: true
          branch: bump/containerd
          delete-branch: true
          title: "chore(deps): update containerd"
          body: |
            ## Automated `containerd` update

            This PR updates the `containerd` binaries to the latest versions.

  cri-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/cri-tools.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/capo-image-elements
          commit-message: "chore(deps): update cri-tools"
          signoff: true
          branch: bump/cri-tools
          delete-branch: true
          title: "chore(deps): update cri-tools"
          body: |
            ## Automated `cri-tools` update

            This PR updates the `cri-tools` binaries to the latest versions.

  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/kubernetes.sh
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/capo-image-elements
          commit-message: "chore(deps): update kubernetes"
          signoff: true
          title: "chore(deps): update kubernetes"
          body: |
            ## Automated Kubernetes Version Update
            This PR updates the Kubernetes versions in the CI workflow to the latest maintained versions.
            Source: https://endoflife.date/kubernetes
          delete-branch: true
          branch: bump/kubernetes

