name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/kubernetes.sh
      - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/capo-image-elements
          commit-message: "chore(deps): update kubernetes"
          signoff: true
          title: "chore(deps): update kubernetes"
          body: |
            ## Automated Kubernetes Version Update
            This PR updates the Kubernetes versions in the CI workflow to the latest maintained versions.
            Source: https://endoflife.date/kubernetes
          delete-branch: true
          branch: bump/kubernetes

